# Generated by Django 4.1.1 on 2023-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Jerseys', 'Jerseys'), ('others', 'others')], max_length=20, null=True),
        ),
    ]
