# Generated by Django 4.1.1 on 2023-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_inquiry_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
